import type { ScopeInput } from "@/lib/scope";

export type ScopeTemplate = {
  id: string;
  name: string;
  industry: string;
  description: string;
  timeline: string;
  prefill: ScopeInput;
};

export const scopeTemplates: ScopeTemplate[] = [
  {
    id: "ecommerce-fashion",
    name: "E-commerce Store (Fashion)",
    industry: "E-commerce",
    description: "Online storefront, catalog, cart, payments, shipping, and order tracking.",
    timeline: "8-12 weeks",
    prefill: {
      projectName: "Fashion E-commerce Store",
      description:
        "Build an online fashion store with product catalog, cart, checkout, secure payments, and order tracking.",
      industry: "E-commerce",
      targetAudience: "Young adults in urban Nigeria shopping for fashion online",
      budgetMin: 700000,
      budgetMax: 2000000,
      timeline: "3 months",
      teamSize: 4,
      keyFeatures: ["Product catalog", "Cart and checkout", "Online payment", "Order tracking"],
      competitors: "Jumia, Konga, Instagram boutiques",
    },
  },
  {
    id: "restaurant-ordering",
    name: "Restaurant Website + Ordering",
    industry: "Food & Hospitality",
    description: "Menu, table bookings, online ordering, delivery integrations, and promotions.",
    timeline: "6-10 weeks",
    prefill: {
      projectName: "Restaurant Ordering Platform",
      description:
        "Create a restaurant website with online menu, table booking, food ordering, and delivery support.",
      industry: "Food & Hospitality",
      targetAudience: "Local dine-in and delivery customers",
      budgetMin: 500000,
      budgetMax: 1500000,
      timeline: "3 months",
      teamSize: 3,
      keyFeatures: ["Menu management", "Table reservations", "Online ordering", "Delivery tracking"],
      competitors: "Chowdeck, Glovo, local restaurant sites",
    },
  },
  {
    id: "real-estate-platform",
    name: "Real Estate Listing Platform",
    industry: "Real Estate",
    description: "Property listings, advanced search filters, agent profiles, and lead capture.",
    timeline: "10-14 weeks",
    prefill: {
      projectName: "Real Estate Listings Platform",
      description:
        "Build a property platform with listings, search filters, map view, and lead forms for agents.",
      industry: "Real Estate",
      targetAudience: "Home buyers, renters, and property agents",
      budgetMin: 1200000,
      budgetMax: 3000000,
      timeline: "6 months",
      teamSize: 5,
      keyFeatures: ["Property listings", "Advanced search", "Agent profiles", "Lead capture forms"],
      competitors: "PropertyPro, PrivateProperty",
    },
  },
  {
    id: "school-management-system",
    name: "School Management System",
    industry: "Education",
    description: "Student records, attendance, results, fees, communication, and reporting.",
    timeline: "10-16 weeks",
    prefill: {
      projectName: "School Management System",
      description:
        "Develop a web app for student records, attendance, result processing, fee tracking, and parent communication.",
      industry: "Education",
      targetAudience: "School administrators, teachers, parents, and students",
      budgetMin: 1000000,
      budgetMax: 2800000,
      timeline: "6 months",
      teamSize: 5,
      keyFeatures: ["Student records", "Attendance", "Results and transcripts", "Fee management"],
      competitors: "Local school ERP solutions",
    },
  },
  {
    id: "hospital-appointment-app",
    name: "Hospital Appointment App",
    industry: "Healthcare",
    description: "Appointment booking, doctor schedules, reminders, and patient profile tracking.",
    timeline: "8-12 weeks",
    prefill: {
      projectName: "Hospital Appointment App",
      description:
        "Create a patient booking app with doctor schedules, appointment reminders, and patient history.",
      industry: "Healthcare",
      targetAudience: "Hospital patients and clinic administrators",
      budgetMin: 900000,
      budgetMax: 2400000,
      timeline: "3 months",
      teamSize: 4,
      keyFeatures: ["Appointment booking", "Doctor schedules", "Reminders", "Patient profile management"],
      competitors: "Hospital in-house systems, health startup apps",
    },
  },
  {
    id: "fintech-wallet",
    name: "Fintech Wallet + Transfers",
    industry: "Fintech",
    description: "Wallet accounts, bank transfers, transaction history, KYC flow, and fraud controls.",
    timeline: "10-14 weeks",
    prefill: {
      projectName: "Digital Wallet Platform",
      description:
        "Build a secure wallet product with onboarding, transfer flows, transaction feed, and compliance checkpoints.",
      industry: "Fintech",
      targetAudience: "Young professionals and small business owners sending daily payments",
      budgetMin: 1500000,
      budgetMax: 4000000,
      timeline: "5 months",
      teamSize: 6,
      keyFeatures: ["Wallet funding", "Peer transfers", "Transaction history", "KYC verification"],
      competitors: "Opay, PalmPay, Moniepoint",
    },
  },
  {
    id: "logistics-delivery-tracker",
    name: "Logistics Delivery Tracker",
    industry: "Logistics",
    description: "Order intake, route planning, rider assignment, live delivery status, and proof of delivery.",
    timeline: "8-12 weeks",
    prefill: {
      projectName: "Delivery Tracking System",
      description:
        "Create a delivery operations platform for dispatching, route visibility, and customer delivery updates.",
      industry: "Logistics",
      targetAudience: "Urban delivery businesses with rider fleets",
      budgetMin: 900000,
      budgetMax: 2600000,
      timeline: "4 months",
      teamSize: 4,
      keyFeatures: ["Dispatch board", "Route optimization", "Live tracking", "Delivery confirmation"],
      competitors: "GIGL internal tools, Kwik",
    },
  },
  {
    id: "hr-recruitment-portal",
    name: "HR Recruitment Portal",
    industry: "HR Tech",
    description: "Job postings, applicant tracking, interview scheduling, scorecards, and hiring pipelines.",
    timeline: "7-11 weeks",
    prefill: {
      projectName: "Recruitment Workflow Portal",
      description:
        "Build a hiring platform that helps teams publish roles, review candidates, and coordinate interviews.",
      industry: "HR Tech",
      targetAudience: "SMEs and growing teams hiring across multiple roles",
      budgetMin: 700000,
      budgetMax: 2200000,
      timeline: "3 months",
      teamSize: 4,
      keyFeatures: ["Applicant tracking", "Interview scheduling", "Candidate scorecards", "Offer workflow"],
      competitors: "Workable, Lever",
    },
  },
  {
    id: "saas-helpdesk",
    name: "SaaS Helpdesk + Knowledge Base",
    industry: "SaaS",
    description: "Ticket management, agent assignments, SLA tracking, and self-serve knowledge base.",
    timeline: "9-13 weeks",
    prefill: {
      projectName: "Customer Support Helpdesk",
      description:
        "Develop a support suite with ticket queues, response automation, and searchable documentation.",
      industry: "SaaS",
      targetAudience: "B2B teams supporting recurring subscription customers",
      budgetMin: 1100000,
      budgetMax: 2900000,
      timeline: "4 months",
      teamSize: 5,
      keyFeatures: ["Ticket inbox", "Agent routing", "SLA reports", "Knowledge base"],
      competitors: "Zendesk, Freshdesk",
    },
  },
  {
    id: "marketplace-multivendor",
    name: "Multi-vendor Marketplace",
    industry: "E-commerce",
    description: "Vendor onboarding, product listings, commissions, payouts, and dispute management.",
    timeline: "12-16 weeks",
    prefill: {
      projectName: "Multi-vendor Marketplace",
      description: "Build a marketplace where multiple sellers list products and buyers checkout securely.",
      industry: "E-commerce",
      targetAudience: "Online shoppers and independent sellers across major cities",
      budgetMin: 1800000,
      budgetMax: 5000000,
      timeline: "6 months",
      teamSize: 7,
      keyFeatures: ["Vendor onboarding", "Commission engine", "Seller payouts", "Dispute center"],
      competitors: "Jiji, Etsy",
    },
  },
  {
    id: "telemedicine-platform",
    name: "Telemedicine Consultation Platform",
    industry: "Healthcare",
    description: "Virtual consults, doctor availability, e-prescriptions, and patient follow-up workflows.",
    timeline: "10-14 weeks",
    prefill: {
      projectName: "Telemedicine Platform",
      description: "Create a virtual consultation platform with scheduling, video, and medical notes.",
      industry: "Healthcare",
      targetAudience: "Patients in urban and semi-urban areas needing remote care",
      budgetMin: 1600000,
      budgetMax: 4200000,
      timeline: "5 months",
      teamSize: 6,
      keyFeatures: ["Doctor scheduling", "Video consults", "E-prescriptions", "Follow-up reminders"],
      competitors: "Doctoora, mPharma care tools",
    },
  },
  {
    id: "e-learning-lms",
    name: "E-learning LMS",
    industry: "Education",
    description: "Course authoring, assessments, progress tracking, certificates, and student dashboards.",
    timeline: "9-13 weeks",
    prefill: {
      projectName: "Learning Management System",
      description: "Build an LMS for online courses, quizzes, learning analytics, and certificates.",
      industry: "Education",
      targetAudience: "Training academies and online educators",
      budgetMin: 1000000,
      budgetMax: 3200000,
      timeline: "4 months",
      teamSize: 5,
      keyFeatures: ["Course builder", "Assessments", "Progress analytics", "Certificates"],
      competitors: "Teachable, Moodle",
    },
  },
  {
    id: "event-ticketing",
    name: "Event Ticketing Platform",
    industry: "Events",
    description: "Event pages, seat/ticket types, checkout, QR validation, and organizer analytics.",
    timeline: "7-11 weeks",
    prefill: {
      projectName: "Event Ticketing Platform",
      description: "Develop a ticketing platform for event discovery, purchase, and check-in validation.",
      industry: "Events",
      targetAudience: "Event organizers and attendees in major cities",
      budgetMin: 900000,
      budgetMax: 2500000,
      timeline: "3 months",
      teamSize: 4,
      keyFeatures: ["Ticket checkout", "QR tickets", "Organizer dashboard", "Sales reports"],
      competitors: "Tix Africa, Eventbrite",
    },
  },
  {
    id: "inventory-pos",
    name: "Retail Inventory + POS",
    industry: "Retail",
    description: "Stock management, POS checkout, supplier records, and low-stock alerts.",
    timeline: "8-12 weeks",
    prefill: {
      projectName: "Retail POS and Inventory",
      description: "Create a POS and inventory suite for retail operations and stock visibility.",
      industry: "Retail",
      targetAudience: "Retail stores and chain operators",
      budgetMin: 850000,
      budgetMax: 2400000,
      timeline: "4 months",
      teamSize: 4,
      keyFeatures: ["POS terminal", "Stock ledger", "Supplier management", "Reorder alerts"],
      competitors: "Vend, Square POS",
    },
  },
  {
    id: "crm-sales-pipeline",
    name: "Sales CRM Pipeline",
    industry: "B2B SaaS",
    description: "Lead capture, pipeline stages, sales activities, and revenue forecasting.",
    timeline: "8-12 weeks",
    prefill: {
      projectName: "Sales CRM Platform",
      description: "Build a CRM with lead tracking, deal pipeline, and activity automation.",
      industry: "B2B SaaS",
      targetAudience: "Sales teams in growth-stage businesses",
      budgetMin: 1200000,
      budgetMax: 3000000,
      timeline: "4 months",
      teamSize: 5,
      keyFeatures: ["Lead capture", "Deal stages", "Task reminders", "Forecast dashboard"],
      competitors: "HubSpot, Pipedrive",
    },
  },
  {
    id: "booking-salon-spa",
    name: "Salon & Spa Booking App",
    industry: "Lifestyle",
    description: "Service catalog, stylist schedules, appointment booking, and customer reminders.",
    timeline: "6-10 weeks",
    prefill: {
      projectName: "Salon Booking App",
      description: "Develop a booking system for salons and spas with availability and reminders.",
      industry: "Lifestyle",
      targetAudience: "Salon owners and recurring clients",
      budgetMin: 600000,
      budgetMax: 1700000,
      timeline: "3 months",
      teamSize: 3,
      keyFeatures: ["Service listings", "Appointment scheduling", "Staff calendars", "SMS reminders"],
      competitors: "Fresha, Booksy",
    },
  },
  {
    id: "ngo-donation-portal",
    name: "NGO Donation & Impact Portal",
    industry: "Nonprofit",
    description: "Campaign pages, donations, donor receipts, and impact reporting dashboards.",
    timeline: "7-11 weeks",
    prefill: {
      projectName: "NGO Donation Platform",
      description: "Create a nonprofit donation platform with campaigns and transparent impact reporting.",
      industry: "Nonprofit",
      targetAudience: "Donors and nonprofit operations teams",
      budgetMin: 700000,
      budgetMax: 2000000,
      timeline: "3 months",
      teamSize: 4,
      keyFeatures: ["Campaign pages", "Payment donations", "Donor receipts", "Impact reports"],
      competitors: "GoFundMe, GlobalGiving",
    },
  },
  {
    id: "microfinance-loan",
    name: "Microfinance Loan Management",
    industry: "Finance",
    description: "Loan applications, approval workflow, repayment schedules, and delinquency alerts.",
    timeline: "10-15 weeks",
    prefill: {
      projectName: "Microfinance Loan System",
      description: "Build a loan lifecycle platform from application to repayment monitoring.",
      industry: "Finance",
      targetAudience: "Microfinance institutions and loan officers",
      budgetMin: 1600000,
      budgetMax: 4200000,
      timeline: "5 months",
      teamSize: 6,
      keyFeatures: ["Loan applications", "Approval workflow", "Repayment tracking", "Risk flags"],
      competitors: "Mambu, local LOS tools",
    },
  },
  {
    id: "manufacturing-erp-lite",
    name: "Manufacturing ERP Lite",
    industry: "Manufacturing",
    description: "Production planning, work orders, inventory usage, and quality check tracking.",
    timeline: "12-18 weeks",
    prefill: {
      projectName: "Manufacturing Operations System",
      description: "Create an operations system for planning production and tracking output quality.",
      industry: "Manufacturing",
      targetAudience: "Small and mid-size factories",
      budgetMin: 2200000,
      budgetMax: 6000000,
      timeline: "6 months",
      teamSize: 7,
      keyFeatures: ["Production planning", "Work orders", "Material tracking", "Quality checks"],
      competitors: "Odoo Manufacturing, Katana",
    },
  },
  {
    id: "travel-booking",
    name: "Travel Booking Portal",
    industry: "Travel",
    description: "Flight/hotel search integrations, bookings, itinerary management, and payment flow.",
    timeline: "10-14 weeks",
    prefill: {
      projectName: "Travel Booking Platform",
      description: "Build a travel portal for package discovery, booking, and itinerary handling.",
      industry: "Travel",
      targetAudience: "Leisure and business travelers",
      budgetMin: 1500000,
      budgetMax: 4500000,
      timeline: "5 months",
      teamSize: 6,
      keyFeatures: ["Search and filter", "Booking flow", "Itinerary dashboard", "Customer support"],
      competitors: "Wakanow, Booking.com",
    },
  },
];

export function getScopeTemplateById(id: string | null) {
  if (!id) return null;
  return scopeTemplates.find((template) => template.id === id) ?? null;
}
